### ISSUE TITLE
[Feature Request] Thumbnails/artworks

### ISSUE THREAD

**Issue by niek-o** [Topis-Lavalink-Plugins/Topis-Source-Managers-Plugin#8]
I would like to have the feature to obtain thumbnails/album covers from the tracks that are being played. Would this be possible to add to the library?

**Comment by TopiSenpai** [comment]
this is already implemented 
the `artworkURL` is encoded in the track

this requires you to decode the track which

when this pr is merged I can return them directly in the json of `/loadtracks`
https://github.com/freyacodes/Lavalink/pull/618
